[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"

  [build.environment]
    PNPM_FLAGS = "--no-frozen-lockfile"

[functions]
  node_bundler = "esbuild"
  
  [functions.timeout]
    default = 30 
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
