[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"

  [build.environment]
    PNPM_FLAGS = "--no-frozen-lockfile"
    NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  
  [functions.timeout]
    default = 30

# Health check endpoint (no redirect needed)
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health-check"
  status = 200

# Test endpoint for debugging
[[redirects]]
  from = "/test-auth/*"
  to = "/.netlify/functions/auth-test/:splat"
  status = 200

# Main API routes - redirect to serverless function
[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
